apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mvcwebstatic
  name: mvcwebstatic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvcwebstatic
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mvcwebstatic
    spec:
      containers:
      - image: myregistry.azurecr.io/staicweb:4.1.52
        imagePullPolicy: IfNotPresent
        name: mvcwebstatic
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: css-file-configmap-volume
          mountPath: /app/wwwroot/css/site.css
          subPath: site.css
      restartPolicy: Always
      volumes:
      - name: css-file-configmap-volume
        configMap:
          name: css-file